SELECT DISTINCT TRANSMISSION_CLASSIFICATION
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.WHO_SITUATION_REPORTS
WHERE COUNTRY='Austria';

SELECT DISTINCT TRANSMISSION_CLASSIFICATION
FROM COVID19_EPIDEMIOLOGICAL_DATA.PUBLIC.WHO_SITUATION_REPORTS
WHERE COUNTRY='India';
